### ISSUE TITLE
i23: implement optical edge detection algorithm in dodal device

### ISSUE THREAD

**Issue by Tom-Willemsen** [DiamondLightSource/dodal#129]
Existing optical edge detection algorithm is in an adPython areadetector plugin (it is a relatively simple script that calls into OpenCV). adPython is becoming unsupported at diamond long term.

Following discussion in MX office, pull this algorithm into the dodal layer to avoid introducing adPython onto i23.

Note: refers to pin tip centring not loop centring.

**Comment by DominicOram** [comment]
There have been historic issues in the CPU usage of the plugin. We should be mindful of this. We may be able to get away with not doing it for every frame but just doing it once for the current frame
