### ISSUE TITLE
Ophyd V2 devices: consider whether the current `device_instantiation` abstraction(s) are correct

### ISSUE THREAD

**Issue by Tom-Willemsen** [DiamondLightSource/dodal#149]
For example, V2 devices don't necessarily take a prefix but have the prefix as part of the name. 

We could:
- Say that all of *our* v2 devices take a prefix regardless, keeping consistency with v1
- Refactor `device_instantiation` to still be semi-generic but build name/prefix combinations correctly for v1 or v2 as appropriate
- Split `device_instantiation` into `_v1` and `_v2` with different behaviour.

Unclear to me exactly what is desirable.

**Comment by stan-dot** [comment]
@coretl this is relevant to #483 and can be either incorporated, closed, or still kept as-is

**Comment by coretl** [comment]
I think this can be closed as not relevant after #483 

@DominicOram do you agree?

**Comment by DominicOram** [comment]
Yh, happy to close. Tbh we won't have any v1 devices round soon anyway
