### ISSUE TITLE
Several unit tests unstable

### ISSUE THREAD

**Issue by Tom-Willemsen** [DiamondLightSource/dodal#202]
Prompted by some repeated unit-test running to investigate https://github.com/DiamondLightSource/dodal/issues/195, we have a range of unstable unit tests.

### Acceptance criteria

- Be able to run `while python -m pytest -m "not s03" ; do :; done` for a reasonable amount of time without any failures. (That command repeatedly runs the test suite, until something fails). 
  * Currently on my machine it takes ~a few minutes on average to run the tests enough times to get a failure.

The most common offenders seem to be:
- `test_given_pin_tip_found_before_timeout_then_timeout_status_cleaned_up_and_tip_value_remains`
- `test_given_stale_parameters_goes_high_before_callbacks_then_stale_parameters_waited_on`
- `test_unsuccessful_false_roi_mode_change_results_in_callback_error` [ex 1](https://github.com/DiamondLightSource/dodal/actions/runs/6496883388/job/17646935568) [ex 2](https://github.com/DiamondLightSource/dodal/actions/runs/6496883388/job/17646875300)
- `test_when_zoom_1_then_flat_field_applied`
- `test_when_led1_not_out_it_switches_on`

If possible, document any common patterns/anti-patterns that are causing these tests to be unstable so that we can avoid them in future.

**Comment by DominicOram** [comment]
For the zoom test, worth doing https://github.com/DiamondLightSource/dodal/issues/203 first
