### ISSUE TITLE
Add support for 3.12

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/dodal#222]
Python 3.12 is now out, we should add support for it to keep up to date.

Depends on p4p compatibility https://github.com/mdavidsaver/p4p/pull/126

## Acceptance Criteria
* Non-test builds are unpinned (e.g. reverse https://github.com/DiamondLightSource/dodal/pull/221/commits/b980f9bf3df0e0042a650dd9d46540d12f7589ab)
* CI runs tests under 3.12 
* CI all still passes
* Documentation is updated to reflect we support 3.12

**Comment by stan-dot** [comment]
update:
original p4p PR was closed.

This PR is where it seems the cutting edge is
https://github.com/mdavidsaver/p4p/pull/141

**Comment by stan-dot** [comment]
latest `main` branch seems to support 3.12 https://github.com/DiamondLightSource/dodal/blob/main/pyproject.toml


can we close this @DominicOram ?

**Comment by DominicOram** [comment]
Not until CI is in properly https://github.com/DiamondLightSource/dodal/blob/46132f0e066debaf906c1a80dcefca175b3f5c01/.github/workflows/ci.yml#L24

**Comment by stan-dot** [comment]
ah right I forgot about this
