### ISSUE TITLE
Split tests into system/unit test folders

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/dodal#233]
As with Hyperion https://github.com/DiamondLightSource/hyperion/issues/970 it would be nice to be able to run all the unit tests at once from vscode. For this, we need to separate the system (`@pytest.mark.s03`) and unit tests at the top level of the tests directory

## Acceptance Criteria
* Directory structure looks like:
```
tests/
  unit tests/
    devices/
    beamlines/
    ...
  system tests/
    devices/
    beamlines/
    ...
```
* you can run all the unit tests with one click in vscode

**Comment by stan-dot** [comment]
alternatively just adding the `@pytest.mark.system` might do the trick without a directory rearrangement

**Comment by dperl-dls** [comment]
We used to use that solution in hyperion but it was annoying not to be able to run only the unit tests from the test explorer in vscode, which is why we switched

**Comment by stan-dot** [comment]
testing now in Dodal

in the test explorer with running `all` I get 655/678 on the main branch and yeah, adding arguments into the filter of sorts `!s03` does not seem to impact the filter.

**Comment by dperl-dls** [comment]
yes, I wish the test runner had a way to add pytest options or marks. if you want to make an improvement to vscode-python or whatever that's in I'd consider it an alternative solution for this issue ;)
