### ISSUE TITLE
Can we get rid of python 3.8 and 3.9 tests?

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/dodal#29]
Our mypy enforces not having implicit optionals (i.e. `x: float = None`) and instead needs something like `x: Union[None,float] = None`, `x: Optional[float] = None` or `x: float | None = None`.

I like the last format best, but it is available in >=3.10 only, and we use python 3.10 features elsewhere (in artemis). Do we need to support 3.8 and 3.9 for other applications, or, since everyone is using venvs anyway, can we just say it's 3.10+?

**Comment by DominicOram** [comment]
I vote we keep support here, I can see the argument for not worrying too much in Artemis as it's not a module anyone should be depending on but 3.8 and 3.9 are generally supported python versions so we should keep supporting them. In which case 2 seems cleanest
