### ISSUE TITLE
Close unused Zocalo connections 

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/dodal#322]
The `ZocaloResults` device was not properly closing connections it created, eventually resulting in too many open sockets:

https://graylog2.diamond.ac.uk/messages/logs_8646/60c892e1-c751-11ee-8ab3-1866dafae904

and possibly also leading to too many connections on the zocalo end.

this brought to light the possibility (uncomfirmed) that even in the `artemis` environment, Hyperion might be using the `ispyb_zocalo` user instead of its own allocated user

**Comment by keeble** [comment]
ah, we've had some mixed messaging here - the above graylog message mentions `pika`, which is the python package used for connecting to rabbitMQ, so this error looks to be related to connections to zocalo rather than connections to ispyb.
