### ISSUE TITLE
 Ophyd-async: implementation of Synchrotron

### ISSUE THREAD

**Issue by DiamondJoseph** [DiamondLightSource/dodal#360]
The current Synchrotron implementation is a vanilla ophyd one. Ophyd-async will be the standard ophyd implementation that Diamond targets, so we should have an implementation of this common device that can be used with ophyd-async going forwards. This should not replace the ophyd implementation until we are certain it can be deprecated.

## Acceptance Criteria

- [ ] class defined for an ophyd-async implementation of the Synchrotron
- [ ] which can connect to the read-only signals presented by the Synchrotron
- [ ] when read out gives sensible data with correct formatting and metadata
- [ ] class can be used in count plan, or [registered with a SupplementalData pre-processor](https://nsls-ii.github.io/bluesky/plans.html#supplemental-data)?

**Comment by DominicOram** [comment]
I'm not adverse to getting rid of the old one as part of this. It's a simple device, and we can easily test it offline so low risk
