### ISSUE TITLE
Move to copier

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/dodal#378]
We should move to the new `copier` template rather than the old skeleton. https://github.com/DiamondLightSource/python-copier-template is the template, https://diamondlightsource.github.io/python-copier-template/main/tutorials/adopt-existing.html is some instructions

## Acceptance Criteria
* We have moved to the copier template
* All CI behaviour is maintained

**Comment by joeshannon** [comment]
I might have some time to take a look at this - I have some experience as I previously converted blueapi.

Probably the most fiddly part was probably moving from the separate "developer" and "user" guides to a single manual. Is that the plan for dodal too?

**Comment by DominicOram** [comment]
Yep, we can combine the docs too
