### ISSUE TITLE
 IVU Compatible Insertion Device

### ISSUE THREAD

**Issue by callumforrester** [DiamondLightSource/dodal#389]
Follow-up to insertion device for I22 requirement in #377. I22 has an IVU insertion device, which is different to the CPMUs used by I03 and I04. Further consultation is needed to see if the PVs are sufficiently similar that the current [Undulator](https://github.com/DiamondLightSource/dodal/blob/c79e88295a066eb1630592b3fa031d6f033bafa8/src/dodal/devices/undulator.py#L16) device can be generalised (and ported to ophyd-async) or if it makes sense to create a new one.

@Tom-Willemsen I see you've done some work on I23, which has the same type as I22, did you ever look into making an ophyd device for the ID.

## Acceptance Criteria
* ophyd-async IVU device available
* Insertion device config included in i22 beamline module
* Fake insertion device config included in p38 beamline module
* Fields specified in #377 are exposed

**Comment by Tom-Willemsen** [comment]
> @Tom-Willemsen I see you've done some work on I23, which has the same type as I22, did you ever look into making an ophyd device for the ID.

No, I don't think I ever looked at this - the work on i23 that I did was for a very narrow use-case (OAV pin-tip detection), I don't think any other devices were added.

**Comment by callumforrester** [comment]
Have consulted with Controls, the I22 Undulator should behave similarly to the I03/I04 one from an EPICS perspective, so the existing ophyd device will hopefully work for both beamlines. In which case this ticket just becomes about porting it to ophyd-async.

**Comment by DominicOram** [comment]
We would presumably want to rename from `Undulator` -> `InsertionDevice` to be more generic?

**Comment by DominicOram** [comment]
Tested running the `ophyd` undulator against I22 and it works without changes, should be easy to convert
