### ISSUE TITLE
Ophyd-async devices for HFM and VFM 

### ISSUE THREAD

**Issue by callumforrester** [DiamondLightSource/dodal#398]
Required for #377

We need to implement an HFM and VFM device exposed the fields required for I22 nexus files (see linked issue).

## Acceptance Criteria
* HFM device available in dodal
* VFM device available in dodal
* HFM and VFM config included in i22 beamline module
* Fake HFM and VFM config included in p38 beamline module
* Fields specified in #377 are exposed

**Comment by callumforrester** [comment]
We could also look into making the resultant devices compatible sub-devices of [`XBPMFeedback`](https://github.com/DiamondLightSource/dodal/blob/3773c90fe59d07c72a0964a4fbbb0d4eddaa44a9/src/dodal/devices/xbpm_feedback.py).
Would probably have to find a way to marry the two nearly-identical `XBPMFeedback` classes back together while we're at it. @DominicOram do you have any thoughts?

**Comment by DominicOram** [comment]
> We could also look into making the resultant devices compatible sub-devices of [XBPMFeedback](https://github.com/DiamondLightSource/dodal/blob/3773c90fe59d07c72a0964a4fbbb0d4eddaa44a9/src/dodal/devices/xbpm_feedback.py).
Would probably have to find a way to marry the two nearly-identical XBPMFeedback classes back together while we're at it. @DominicOram do you have any thoughts?

That sounds like scope creep to me. I'm not sure if I agree/disagree if we should do it but I don't think it adds anything immediately

**Comment by DominicOram** [comment]
i03 doesn't use it's `HFM` but we do use the `VFM`. If we wanted to make a generic `FocussingMirror` we would have the following issues:
* i03 has a fine_pitch that i22 doesn't have. This isn't actually used on i03 so we can remove
* i03 has a `VERT` and `LAT`, I think these correlate to `Y` and `X` in i22 but we would need to discuss with controls/scientists

**Comment by DominicOram** [comment]
https://github.com/DiamondLightSource/dodal/issues/377 specifies that you want to read incident angle into the nexus file. Presumably this is calculated from the other axes? @Tom-Willemsen or @callumforrester do we have an idea of how it's derived?

**Comment by Tom-Willemsen** [comment]
^ I've asked one of the i22 scientists how `incident_angle` gets derived. Will update when I get a reply.

**Comment by Tom-Willemsen** [comment]
On i22, incident angle is just "pitch", for both the horizontal and vertical focusing mirrors.
