### ISSUE TITLE
Update adsim to ophyd_async

### ISSUE THREAD

**Issue by DiamondJoseph** [DiamondLightSource/dodal#404]
The AreaDetector simulator backed by the Epics AreaDetectorSimulator is split into three parts: `dodal/src/dodal/devices/adsim.py` contains a 5-axis MotorBundle; `dodal/src/dodal/devices/areadetector/adsim.py` contains a simulated detector; `dodal/src/dodal/adsim.py` is equivalent to a beamline. Having these maintained and using ophyd_async may enable fast testing of plan behaviour and would give an easily run up simulated beamline for local development.

## Acceptance Criteria
* Blueapi can be run up with the areadetector simulator devices exposed and connected with ophyd_async signals and an example grid_scan may be run with data being emitted

**Comment by DominicOram** [comment]
The simulator is a generic EPICS thing, right? Would this make more sense inside `ophyd-async` @coretl?

**Comment by DiamondJoseph** [comment]
https://github.com/bluesky/ophyd-async/tree/main/src/ophyd_async/epics/adsimdetector

There is an adsimdetector in ophyd-async

**Comment by DominicOram** [comment]
As part of this make sure https://github.com/DiamondLightSource/dodal/pull/737#discussion_r1711422672 has coverage
