### ISSUE TITLE
Device instantiation tests intermittently failing due to no event loop 

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/dodal#414]
E.g. https://github.com/DiamondLightSource/dodal/actions/runs/8550414641/attempts/1
`--random-order-seed=818181` (from the run linked) does not reproduce this locally
` --random-order-seed=375256` does for me on main at time of writing

## Acceptance Criteria
* This doesn't happen any more

**Comment by DiamondJoseph** [comment]
It's not just the device_instantiation test, it's possibly any/all using the RE fixture:
https://github.com/DiamondLightSource/dodal/actions/runs/8600634205/job/23566004115?pr=421

**Comment by dperl-dls** [comment]
Yes, it looks like a race condition between creating the RE and the device, we should test the RE for liveness before yielding it from the fixture
