### ISSUE TITLE
Create an RE fixture for tests

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/dodal#449]
In Hyperion we have an RE fixture for tests that neatly cleans itself up (https://github.com/DiamondLightSource/hyperion/blob/a8bc8b229581144296f9a88692bbf8f67f547348/tests/conftest.py#L139). We should consider moving it into `dodal`

## Acceptance Criteria
* `dodal` has a similar `RE` fixture to Hyperion

**Comment by olliesilvester** [comment]
Done
