### ISSUE TITLE
Create HTSS beamline module 

### ISSUE THREAD

**Issue by DiamondJoseph** [DiamondLightSource/dodal#456]
Create HTSS beamline module, with the current setup of the SSCC Training Room beamlines-in-a-box, ensure it is up to date. 

Note that these should be created with a single SampleStage device, with x and theta child device components, to ensure that dotted access to these fields is possible.

## Acceptance Criteria
* P49 beamline can be run up off of a beamline in a dodal release
* A plan can be run on P49 using dotted access to the child devices of SampleStage

**Comment by stan-dot** [comment]
@DiamondJoseph  is this a still requested feature?

**Comment by DiamondJoseph** [comment]
This was completed by #743
