### ISSUE TITLE
 Use tolerances in beamline parameters file for aperture scatterguard

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/dodal#494]
For the aperture scatterguard to be in position we currently use the motor tolerances, we should instead use those in the beamline parameters file see https://diamondlightsource.slack.com/archives/C048RD0KFFF/p1714579073626219

## Acceptance Criteria
* Tolerances from beamline parameters file are used in the aperture/scatterguard

**Comment by dperl-dls** [comment]
Should there be signals for this or just attributes?

**Comment by DominicOram** [comment]
* Signal for outside device, attribute otherwise. This is an attribute as will only be internal
* We already read the file, need to get the tolerances out as well as positions and use those
* This is just aperture scatterguard for now, ignore the other tolerances in this file
* Small
