### ISSUE TITLE
 Only allow PRs to be merged if the PR branch is up to date with main

### ISSUE THREAD

**Issue by DiamondJoseph** [DiamondLightSource/dodal#515]
This is configurable in the github settings for the repository. It would prevent merged PRs from breaking main by being incompatible with changes that have gone in since the branch was taken.

## Acceptance Criteria
* The github UI prevents merging for a branch that does not extend from head of main.

**Comment by DominicOram** [comment]
I agree with it, lets just do it

**Comment by DiamondJoseph** [comment]
![Screenshot from 2024-05-09 12-17-22](https://github.com/DiamondLightSource/dodal/assets/53935796/43ff7df7-aa91-453e-bb08-0deb99cffdd3)

Here's the relevant option, can also require various checks to have passed before allowing a merge: should I enable this and enforce that testing on the latest version of python has passed?

**Comment by DominicOram** [comment]
Yh, I think we can require that testing on all versions of python passed. Some of the other tests, like codecov, are potentially more flaky/controversial but the tests should all pass at least

**Comment by DiamondJoseph** [comment]
Complete, PRs now require being up to date with main and also that the `test` action (which is the matrix of testing on all python versions) has passed.
