### ISSUE TITLE
Misleading slits device name

### ISSUE THREAD

**Issue by keithralphs** [DiamondLightSource/dodal#529]
https://github.com/DiamondLightSource/dodal/blob/050e9a4405e6a87e39843682df9963f6d8be3ced/src/dodal/beamlines/_device_helpers.py#L29

From @Tom-Willemsen: Should be called "slits" rather than "slit_gaps".

Tagging @callumforrester @joeshannon

**Comment by Tom-Willemsen** [comment]
> From @Tom-Willemsen: Should be called "slits" rather than "slit_gaps".

Because the device has members for both gaps and centres - so I'd expect something like `slits_1` at the user level. Looks weird to talk to `s1_slit_gaps.x_centre` for example.

**Comment by keithralphs** [comment]
Are you happy with the form s1_slits, s2_slits, etc.?

**Comment by callumforrester** [comment]
I think `slits_1`, `slits_2` etc. is better as that mirrors the dodal factory function  names

**Comment by Tom-Willemsen** [comment]
I'd prefer it to be the same as the dodal device name - i.e. `slits_1` I think.

Wasn't there discussion at some point about having `blueapi` automatically set the name of the device to the name in the dodal module anyway? Or perhaps I'm misremembering. If that's the case, then it would definitely be misleading to have different names depending on whether we're running in blueapi or not...

**Comment by callumforrester** [comment]
@Tom-Willemsen there have been a few discussions around that, would be ideal if _dodal_ set the name to the function name so you don't have to supply it all, that would save a lot of boilerplate. Might come out in the wash as part of the tickets coming out of #415
