### ISSUE TITLE
 Move some setup_oav utils from hyperion to dodal

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/dodal#539]
There are a number of setup utils for the oav, which would be useful to put into somewhere more common. Specifically `get_move_required_so_that_beam_is_at_pixel` from https://github.com/DiamondLightSource/hyperion/blob/862d2a2b033d1a650a68057466725dbe19889f6d/src/hyperion/device_setup_plans/setup_oav.py#L115 is very useful. 

## Acceptance Criteria
* `get_move_required_so_that_beam_is_at_pixel` and any associated dependencies and tests are moved into `dodal` `plans`
* Hyperion now points at these common plans

**Comment by olliesilvester** [comment]
Is Dodal going to be used as a library for beamline-generic bluesky plans as well as a library for ophyd-async devices?

**Comment by DominicOram** [comment]
Yes, it's fine to put some small plans in there if they are more to do with controlling specific devices than controlling the beamline as a whole

**Comment by olliesilvester** [comment]
Makes sense, We could either have

**Comment by olliesilvester** [comment]
As a convention for stuff like this, we could put useful plans for some device `a` into a file `a.plans`, or maybe `a.utils`? I don't really have a preference, but a convention would be good
