### ISSUE TITLE
 Update to ophyd-async 0.3a5

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/dodal#554]
There is a new version of `ophyd-async` we should move to it

## Acceptance Criteria
* We move to the new version
* Tests still pass

**Comment by DominicOram** [comment]
We will need to fix https://github.com/DiamondLightSource/dodal/issues/551

**Comment by dperl-dls** [comment]
As far as I can tell, only https://github.com/DiamondLightSource/dodal/pull/555 is needed - all tests in dodal and hyperion main pass against 0.3a5 on that branch
