### ISSUE TITLE
Handle exceptions in make_all_devices

### ISSUE THREAD

**Issue by DiamondJoseph** [DiamondLightSource/dodal#58]
(As I understand it): dodal in Artemis/Hyperion lazily instantiates devices when plans that use the devices are required, so as to allow those plans to run regardless of the state of other devices on the beamline, and in this case if a device fails to instantiate the exception should be thrown.

make_all_devices is called by tests and when dodal is imported into Blueapi, which wants to know about all devices and register them to its context eagerly: in an analogous way, Blueapi would like to successfully start but not allow any devices that failed to be instantiated to be used as arguments for plans.

Tangentially related to but potentially opposed to desired behaviour of #3 (Presumably will call make_all_devices, but would be happy allowing an exception to be fatal in this case?)

**Comment by stan-dot** [comment]
@coretl , @DominicOram is this relevant at the moment?

**Comment by DominicOram** [comment]
I believe this is covered by the lazy loading requirements in https://github.com/DiamondLightSource/dodal/pull/597 so closing it
