### ISSUE TITLE
Investigate why the undulator is not working on i22 

### ISSUE THREAD

**Issue by abbiemery** [DiamondLightSource/dodal#586]
When trying to run the stopflow plan on i22 the undulator was having connection errors, so we had to skip it.

**Comment by stan-dot** [comment]
undulator DOES connect with `dodal connect i22`. Haven't tested in the stopflow plan yet. Need to leave the pasteable line to run it somewhere

**Comment by stan-dot** [comment]
apparently there are also beam intensity drop issues, to be sorted from the controls perspective during the next shutdown. closing this for now, as we didn't capture much diagnostic information anyway
