### ISSUE TITLE
 Create device for i22 slits_4

### ISSUE THREAD

**Issue by DiamondJoseph** [DiamondLightSource/dodal#587]
i22's slits_4 has different PVs than its other slits, a representation of this device is required along with the existing slits.

## Acceptance Criteria
* Specific criteria that will be used to judge if the issue is fixed

**Comment by abbiemery** [comment]
Once this is fixed, put them back into the plan (un-comment them out)

**Comment by stan-dot** [comment]
> Slit 	x_centre, x_gap, y_centre, y_gap 	

and 
name, physical, derived axes:
Slit 	X_plus, X_minus, Y_plus, Y_minus 	X_centre, Y_centre, X_size, Y_size
