### ISSUE TITLE
Temorary I22 DCM 

### ISSUE THREAD

**Issue by callumforrester** [DiamondLightSource/dodal#593]
I22 needs a DCM object urgently, the PVs arbitrarily differ from the existing DCM. Reconciliation in the future should be possible, I have made an issue: https://github.com/DiamondLightSource/dodal/issues/592

## Acceptance Criteria
* DCM class using I22 PV names
* Tests pass (including manual dodal CLI tests)

**Comment by DominicOram** [comment]
This was caught on the original issue https://github.com/DiamondLightSource/dodal/issues/397#issuecomment-2020373884 is there something we could have done to make sure we didn't lose sight of it?

**Comment by callumforrester** [comment]
Yes... I should have re-read it more carefully, sorry!
Beyond that I don't know, we should probably discuss...

The thing we didn't catch until now is that we actually _do_ need the wavelength PV (or to calculate it by other means), so that's a new problem to deal with, @DiamondJoseph
