### ISSUE TITLE
 `TetrammController` does not take an `arm` argument

### ISSUE THREAD

**Issue by callumforrester** [DiamondLightSource/dodal#610]
I get the following when trying to `count` a `TetrammDetector`:

```shell
TypeError("TetrammController.arm() missing 1 required positional argument: 'exposure'")>
```

Reference: https://github.com/DiamondLightSource/i22-bluesky/issues/35#issuecomment-2160438565

## Acceptance Criteria
* Tetramm can be `count`ed with a `RunEngine`
* Test to prevent regression

**Comment by callumforrester** [comment]
The reason after discussion with @coretl is that the tetramm doesn't support software triggered scanning. When `trigger()` is called via a software scan it does not pass `exposure` to `controller.arm`. We will keep this status quo for now but should make the error message clearer.

**Comment by joeshannon** [comment]
Note from discussion, also change type signature on `arm` to `exposure: float | None`.
