### ISSUE TITLE
 Tetramm TriggerMode enum broken by ophyd-async update

### ISSUE THREAD

**Issue by DiamondJoseph** [DiamondLightSource/dodal#649]
Tests are expecting that the TriggerMode of the TetraAMM is the enum value, but this appears to not hold anymore.

## Acceptance Criteria
* Specific criteria that will be used to judge if the issue is fixed

**Comment by evalott100** [comment]
This was a bug in the `SoftSignalBackend` itself, no changes need to be made in dodal.
