### ISSUE TITLE
Remove thumbnail writing 

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/dodal#655]
Following https://jira.diamond.ac.uk/browse/LIMS-1134 we no longer need to write out thumbnail images, we should remove this code.

## Acceptance Criteria
* Thumbnail writing is removed

**Comment by DominicOram** [comment]
From https://github.com/DiamondLightSource/hyperion/issues/1465#issuecomment-2225296686 this is actually causing issues in hyperion so bumping it's prioirity

**Comment by dperl-dls** [comment]
we think XS
