### ISSUE TITLE
Add catalog-info.yaml support to see the repo in the software-catalog 

### ISSUE THREAD

**Issue by stan-dot** [DiamondLightSource/dodal#662]
Many other DLS repos already have this.

In reference to https://github.com/DiamondLightSource/developer-portal/issues/694

**Comment by stan-dot** [comment]
@rtuck99  this issue will be included in the scope of [this one](https://github.com/DiamondLightSource/dodal/issues/378), right?

**Comment by stan-dot** [comment]
adding this PR as reference https://github.com/DiamondLightSource/dodal/pull/667

**Comment by rtuck99** [comment]
This issue already covered by #378
