### ISSUE TITLE
Move to pydantic v2 

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/dodal#679]
We should make sure that all our dependencies etc. work on pydantic v2

## Acceptance Criteria
* We pin `pydantic>2`
* Unpin zocalo < 1.0.0
* We remove all the ignores around pydantic in `filterwarnings`
* Dependencies are happy to install on `pip install`
* Unit tests work

**Comment by DominicOram** [comment]
Currently blocked on:
* https://github.com/bluesky/scanspec/issues/122
* https://github.com/DiamondLightSource/python-zocalo/issues/247

**Comment by dperl-dls** [comment]
Once we can, we should then update some of the way we use pydantic features, e.g.: https://github.com/DiamondLightSource/dodal/blob/fe3f48cc7e65e05ca50025d22a2161bef4eadba3/src/dodal/devices/detector/detector.py#L59

**Comment by dperl-dls** [comment]
We are now blocked by scanspec requiring numpy>=2.0 and p4p requiring numpy<2.0

blueapi and nexgen also still pinned to pydantic<2

**Comment by DominicOram** [comment]
Waiting for another release of p4p

**Comment by DiamondJoseph** [comment]
I believe we're currently *not* blocked by p4p- only Numpy 2 support is. I'm going to make the required changes and check

**Comment by dperl-dls** [comment]
@DiamondJoseph yes, but unfortunately the version of scanspec which supports pydantic 2 also requires numpy 2, so we are indirectly still blocked by that

**Comment by DiamondJoseph** [comment]
Not since [ScanSpec 0.7.2](https://github.com/bluesky/scanspec/releases/tag/0.7.2)
