### ISSUE TITLE
 Transfocator: Convert to ophyd-async

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/dodal#748]
We should convert the i04 transfocator to ophyd-async. As discussed at https://github.com/DiamondLightSource/dodal/issues/399 the transfocator and f-switch are basically the same device. However, the i22 one does not have some of the features that the i04 one has. In doing this conversion we should try and make sure the two share as much code as reasonable. This may involve a bit of discussion with controls/scientists to get the features on i04's added to i22's IOC as well.

## Acceptance Criteria
* I04's transfocator no longer uses `ophyd` but instead uses `ophyd-async`

**Comment by olliesilvester** [comment]
Discussed with @shihab-dls , as part of this issue, we will also document any changes required in EPICS in order to share code between i22's f-switch and the i04 transfocator
