### ISSUE TITLE
I22 connection tests did not fail when they weren't mocking

### ISSUE THREAD

**Issue by callumforrester** [DiamondLightSource/dodal#850]
#847 appears to have been caused by #841 not passing `mock=True` to the `DeviceInitializationController`, that should have caused a timeout failure when the CI tried to connect to PVs that don't exist on its network, instead the tests passed after a very long time, suggesting that something was timing out but not failing the test, perhaps an exception was being swallowed.

This issue is to investigate and prevent recurrence

## Acceptance Criteria
* The cause of the non-failure is known
* A regression test/tests are in place to prevent recurrence

**Comment by DiamondJoseph** [comment]
make_all_devices returns the connected devices and also collects all of the exceptions that were raised.
As discussed, the tests should have accounted for checking the collected exceptions.

**Comment by rtuck99** [comment]
This is fixed in #858
