### ISSUE TITLE
 Dodal connect --all is broken

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/dodal#875]
When I run `dodal connect --help` I am told I should be able to run `dodal connect --all` to try and connect to all known beamlines. However, when I try this I get `Error: Missing argument '{i04|i24|b01_1|s03|i03|i04-1|i04_1|i13-1|i13_1|i20-1|i20_1|i23|p99|p49|p46|training_rig|p48|p47|i22|p38|p45}'`.

## Acceptance Criteria
* `dodal connect --all` and `dodal connect -a` work as expected

**Comment by rtuck99** [comment]
dodal connect --all isn't actually intended to connect to all beamlines. Instead it connects to devices in the named beamline that are ordinarily skipped due to decorators.

**Comment by DominicOram** [comment]
My bad, I still think this is useful though, thanks!

**Comment by DominicOram** [comment]
Closing as won't do for now
